/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.Dimension;
import java.awt.Graphics;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author batro
 */
public class fmIndex extends javax.swing.JFrame {
    File Directory = new File("");
    String pathConnection=Directory.getAbsolutePath()+"/data/Connection.txt";
    String path=Directory.getAbsolutePath();
    /**
     * Creates new form fmIndex
     */
    public fmIndex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            File path= new File("");
            ImageIcon icon = new ImageIcon(path.getAbsolutePath()+"/img/images.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        }
        ;
        btnLogin = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCreateDatabase = new javax.swing.JButton();
        lblCreate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý phòng máy");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(993, 557));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pay-per-click-icon.png"))); // NOI18N
        btnLogin.setVisible(false);
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblLogin.setVisible(false);
        lblLogin.setForeground(new java.awt.Color(255, 51, 51));
        lblLogin.setText("Đăng nhập để sử dụng phần mềm!");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/My-Computer-icon.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/My-Computer-icon.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/My-Computer-icon.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 102));
        jLabel1.setText("PHẦN MỀM QUẢN LÝ PHÒNG MÁY");

        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("------------------------------------------------------------------------");

        btnCreateDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Misc-New-Database-icon.png"))); // NOI18N
        btnCreateDatabase.setText("tạo Data");
        btnCreateDatabase.setVisible(false);
        btnCreateDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDatabaseActionPerformed(evt);
            }
        });

        lblCreate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCreate.setVisible(false);
        lblCreate.setForeground(new java.awt.Color(153, 0, 102));
        lblCreate.setText("Bạn chưa có data vui lòng khởi tạo Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(lblLogin)
                                        .addComponent(btnLogin)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(btnCreateDatabase))
                                            .addComponent(lblCreate)))
                                    .addComponent(jLabel4))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCreate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreateDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login f= new login();
        f.show();
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private boolean checkDataBase()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            FileReader fr= new FileReader(pathConnection);
                
            int i;

            String c="";

            do{
                i=fr.read();
                c+=(char)i;
            }while(i!=-1);

            String a[]= c.split(" ");

            String url="jdbc:mysql://" + a[0]+":"+a[1] +"/qlpm";

            Connection con= DriverManager.getConnection(url,a[2],a[3]);
            
            return true;
        } catch (Exception e) {
            return false;
        }
        
    }
    private void btnCreateDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDatabaseActionPerformed
        if(checkSetingConneciton())
        { 
            try {
                FileReader fr= new FileReader(path+"/data/DataBase.txt");
                int i;
                String kq="";
                do{
                    i=fr.read();
                    kq+=(char)i;

                }while(i!=-1);

                String arr[]=kq.split("--");

                Data.DataProvider data= new Data.DataProvider();

                Statement st= data.Get_Connection_Master().createStatement();
                st.execute(arr[0]);

                st=data.Get_Connection().createStatement();
                for(int a=1; a<arr.length-1;a++)
                {
                    st.execute(arr[a]);
                }

                JOptionPane.showMessageDialog(null,"Tạo dữ liệu thành công!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Vui lòng kiểm tra lại thao tác!","Lỗi",2);
                 System.err.println(e.toString());
            }
        }else
        {
            frmSetConnection f= new frmSetConnection();
            f.show();
        }
               
    }//GEN-LAST:event_btnCreateDatabaseActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
      
    }//GEN-LAST:event_jPanel1AncestorAdded
    //Kiểm tra kết nối từ file có thành công hay không
    private  boolean  checkSetingConneciton()
    {
        if(LoadSetting())
        {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                
                FileReader fr= new FileReader(pathConnection);
                
                int i;
                
                String c="";
                
                do{
                    i=fr.read();
                    c+=(char)i;
                }while(i!=-1);
                
                String a[]= c.split(" ");
                
                String url="jdbc:mysql://" + a[0]+":"+a[1] +"/";
                
                Connection con= DriverManager.getConnection(url,a[2],a[3]);
                
                return  true;
            } catch (Exception e) {
                System.err.println(e.toString());
                return false;
            }
        }else
            return false;
    }
    //Kiểm tra file có dữ liệu chưa
    private boolean LoadSetting()
    {
        try {
            FileReader fr= new FileReader(pathConnection);
            if(fr.read()==-1)
            {
                fr.close();
                return false;
            }
            else
            {
                fr.close();
                return true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Không tìm thấy file hệ thống! vui lòng kiểm tra lại phần mềm","Lỗi!",2);
            System.exit(0);
            return false;
        }
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        
        
           if(checkDataBase()==true)
           {
               lblLogin.setVisible(true);
               btnLogin.setVisible(true);
               lblCreate.setVisible(false);
               btnCreateDatabase.setVisible(false);
           }else
           {
               lblLogin.setVisible(false);
               btnLogin.setVisible(false);
               lblCreate.setVisible(true);
               btnCreateDatabase.setVisible(true);           
           }
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDatabase;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblLogin;
    // End of variables declaration//GEN-END:variables
}
